//addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.0.0-M8")
//addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.0.9")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.21")
//addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.13")
//addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.0.8-0.6")
addSbtPlugin("com.lihaoyi" % "workbench" % "0.4.1")
